#!/usr/bin/python3

import socket

def start_client():
    server_ip = input("Enter server IP address: ")
    server_port = 1303

    client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    client_socket.connect((server_ip, server_port))

    data = client_socket.recv(1024).decode()
    print(f"Received from server: {data}")

    client_socket.close()
    print("Connection closed.")

if __name__ == "__main__":
    start_client()
