#!/usr/bin/python3

import socket
from datetime import datetime

def start_server():
    server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server_socket.bind(("0.0.0.0", 1303))
    server_socket.listen(1)

    print("Server is listening on port 1303...")

    while True:
        client_socket, client_address = server_socket.accept()
        print(f"Connection from {client_address}")

        current_time = datetime.now().strftime("%d.%m.%Y %H:%M")
        client_socket.send(current_time.encode())

        client_socket.close()
        print("Connection closed. Waiting for the next connection...")

if __name__ == "__main__":
    start_server()
